import Cover from "./Cover";
import Platform from "./Platform";
import AlternativeName from "./AlternativeName";

type Game = {
    age_ratings: number[];
    aggregated_rating: number;
    aggregated_rating_count: number;
    alternative_names: AlternativeName[];
    bundles: number[];
    category: number;
    checksum: string;
    collection: number;
    cover: Cover;
    created_at: number;
    expansions: number[];
    external_games: number[];
    first_release_date: number;
    follows: number;
    franchise: number;
    franchises: number[];
    game_engines: number[];
    game_localizations: number[];
    game_modes: number[];
    genres: number[];
    id: number;
    involved_companies: number[];
    keywords: number[];
    multiplayer_modes: number[];
    name: string;
    platforms: Platform[];
    player_perspectives: number[];
    rating: number;
    rating_count: number;
    release_dates: number[];
    remasters: number[];
    screenshots: number[];
    similar_games: number[];
    slug: string;
    storyline: string;
    summary: string;
    tags: number[];
    themes: number[];
    total_rating: number;
    total_rating_counter: number;
    updated_at: number;
    url: string;
    videos: number[];
    websites: number[];
};

export default Game;
